[package]
name = "coffilhg/coffeeobjects"
author = "Coffilhg"
content_root = "src"
version = "2.3.5"
license = "Apache-2.0"

[dependencies]
PerfectSignal = "github.com/Coffilhg/PerfectSignal@1.0.1"
CoffeeParser = "github.com/Coffilhg/Useful-Modules@CoffeeParser/1.0.3"