[package]
name = "coffilhg/cameracontroller"
author = "Coffilhg"
content_root = "src"
version = "1.0.0"
license = "LGPL-3.0/?version=3.0+"

[dependencies]
EasySmoothDamp = "github.com/Coffilhg/Useful-Modules@EasySmoothDamp/1.0.2"  