[package]
name = "coffilhg/modulenamelowercase"
description = "ModuleDescription"
version = "ModuleVersion"
license = "MPL-2.0"
authors = ["Coffilhg <coffilhg@gmail.com>"]
repository = "https://github.com/Coffilhg/Useful-Modules/tree/PascalCasedModuleName"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]